error
Error: 3 INVALID_ARGUMENT: Input text not set.
    at Object.callErrorFromStatus (/home/azureuser/suibot/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/home/azureuser/suibot/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (/home/azureuser/suibot/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/home/azureuser/suibot/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /home/azureuser/suibot/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 3,
  details: 'Input text not set.',
  metadata: Metadata {
    internalRepr: Map(1) { 'grpc-server-stats-bin' => [Array] },
    options: {}
  }
}
payload :>>  [
 {
  "platform": "PLATFORM_UNSPECIFIED",
  "text": {
   "text": [
    "'Ups! ¿Podrías repetirlo, por favor?'"
   ]
  },
  "message": "text"
 }
]
Message_from:  {
  id: 'false_573107901940@c.us_3EB07448A554BB54FA8A',
  type: 'ciphertext',
  subtype: 'fanout',
  t: 1651491038,
  notifyName: 'Fernando Ardila',
  from: '573107901940@c.us',
  to: '573216131576@c.us',
  self: 'in',
  ack: 1,
  isNewMsg: true,
  star: false,
  recvFresh: true,
  isFromTemplate: false,
  broadcast: false,
  mentionedJidList: [],
  isVcardOverMmsDocument: false,
  isForwarded: false,
  labels: [],
  hasReaction: false,
  ephemeralOutOfSync: false,
  productHeaderImageRejected: false,
  lastPlaybackProgress: 0,
  isDynamicReplyButtonsMsg: false,
  isMdHistoryMsg: false,
  requiresDirectConnection: null,
  pttForwardedFeaturesEnabled: true,
  chatId: '573107901940@c.us',
  fromMe: false,
  sender: {
    id: '573107901940@c.us',
    name: 'Fercho',
    shortName: 'Fercho',
    type: 'in',
    isBusiness: false,
    isEnterprise: false,
    labels: [],
    isContactSyncCompleted: 0,
    formattedName: 'Fercho',
    displayName: 'Fercho',
    formattedShortName: 'Fercho',
    formattedShortNameWithNonBreakingSpaces: 'Fercho',
    isMe: false,
    mentionName: 'Fercho',
    isMyContact: true,
    isPSA: false,
    isUser: true,
    isWAContact: true,
    profilePicThumbObj: {},
    msgs: null
  },
  timestamp: 1651491038,
  isGroupMsg: false,
  isMedia: false,
  isNotification: false,
  isPSA: false,
  chat: {
    id: '573107901940@c.us',
    labels: [],
    lastReceivedKey: {
      fromMe: false,
      remote: '573107901940@c.us',
      id: '3EB0C433C7AC3D403F5C',
      _serialized: 'false_573107901940@c.us_3EB0C433C7AC3D403F5C'
    },
    unreadCount: 0,
    muteExpiration: 0,
    hasUnreadMention: false,
    archiveAtMentionViewedInDrawer: false,
    hasChatBeenOpened: false,
    tcToken: {},
    tcTokenTimestamp: 1651491044,
    pendingInitialLoading: false,
    msgs: null,
    kind: 'chat',
    isGroup: false,
    contact: {
      id: '573107901940@c.us',
      name: 'Fercho',
      shortName: 'Fercho',
      type: 'in',
      isBusiness: false,
      isEnterprise: false,
      labels: [],
      isContactSyncCompleted: 0,
      formattedName: 'Fercho',
      displayName: 'Fercho',
      formattedShortName: 'Fercho',
      formattedShortNameWithNonBreakingSpaces: 'Fercho',
      isMe: false,
      mentionName: 'Fercho',
      isMyContact: true,
      isPSA: false,
      isUser: true,
      isWAContact: true,
      profilePicThumbObj: {},
      msgs: null
    },
    groupMetadata: null,
    presence: { id: '573107901940@c.us', chatstates: [] },
    isOnline: null,
    lastSeen: null
  },
  isOnline: null,
  lastSeen: null,
  mediaData: {},
  linkPreview: false,
  initialPageSize: 768
}
Result message :>> Fercho :>> OK
INTENT EMPAREJADO:  Default Welcome Intent
payload :>>  [
 {
  "platform": "PLATFORM_UNSPECIFIED",
  "text": {
   "text": [
    "`Hola ${message.chat.contact.displayName}` + ' es un gusto que estés aquí 😊!  Bienvenido al WhatsApp de la mesa de ayuda de la Superintendencia de Servicios Públicos Domiciliarios. *#SUIBOT* 🤖🤙🏻'"
   ]
  },
  "message": "text"
 },
 {
  "platform": "PLATFORM_UNSPECIFIED",
  "text": {
   "text": [
    "'Para continuar...por favor indícame el motivo de tu solicitud... \\n *1. Registrar un trámite*'"
   ]
  },
  "message": "text"
 }
]
Message_from:  {
  id: 'false_573107901940@c.us_3EB07B73408E2AD87BF8',
  body: 'buenas',
  type: 'chat',
  t: 1651491042,
  notifyName: 'Fernando Ardila',
  from: '573107901940@c.us',
  to: '573216131576@c.us',
  self: 'in',
  ack: 1,
  isNewMsg: true,
  star: false,
  recvFresh: true,
  isFromTemplate: false,
  broadcast: false,
  mentionedJidList: [],
  isVcardOverMmsDocument: false,
  isForwarded: false,
  labels: [],
  hasReaction: false,
  ephemeralOutOfSync: false,
  productHeaderImageRejected: false,
  lastPlaybackProgress: 0,
  isDynamicReplyButtonsMsg: false,
  isMdHistoryMsg: false,
  requiresDirectConnection: false,
  pttForwardedFeaturesEnabled: true,
  chatId: '573107901940@c.us',
  fromMe: false,
  sender: {
    id: '573107901940@c.us',
    shortName: 'Fercho',
    pushname: 'Fernando Ardila',
    type: 'in',
    isBusiness: false,
    isEnterprise: false,
    labels: [],
    isContactSyncCompleted: 0,
    formattedName: '+57 310 7901940',
    displayName: 'Fernando Ardila',
    formattedShortName: 'Fercho',
    formattedShortNameWithNonBreakingSpaces: 'Fercho',
    isMe: false,
    mentionName: 'Fernando Ardila',
    notifyName: 'Fernando Ardila',
    isMyContact: false,
    isPSA: false,
    isUser: true,
    isWAContact: true,
    profilePicThumbObj: { id: '573107901940@c.us', tag: '' },
    msgs: null
  },
  timestamp: 1651491042,
  content: 'buenas',
  isGroupMsg: false,
  isMedia: false,
  isNotification: false,
  isPSA: false,
  chat: {
    id: '573107901940@c.us',
    labels: [],
    lastReceivedKey: {
      fromMe: true,
      remote: '573107901940@c.us',
      id: 'VEAIU4VBBLC7VFSOYVYR',
      _serialized: 'true_573107901940@c.us_VEAIU4VBBLC7VFSOYVYR'
    },
    t: 1651491040,
    unreadCount: 0,
    muteExpiration: 0,
    notSpam: true,
    hasUnreadMention: false,
    archiveAtMentionViewedInDrawer: false,
    hasChatBeenOpened: false,
    tcToken: {},
    tcTokenTimestamp: 1651491044,
    tcTokenSenderTimestamp: 1651491040,
    pendingInitialLoading: false,
    msgs: null,
    kind: 'chat',
    isGroup: false,
    contact: {
      id: '573107901940@c.us',
      shortName: 'Fercho',
      pushname: 'Fernando Ardila',
      type: 'in',
      isBusiness: false,
      isEnterprise: false,
      labels: [],
      isContactSyncCompleted: 0,
      formattedName: '+57 310 7901940',
      displayName: 'Fernando Ardila',
      formattedShortName: 'Fercho',
      formattedShortNameWithNonBreakingSpaces: 'Fercho',
      isMe: false,
      mentionName: 'Fernando Ardila',
      notifyName: 'Fernando Ardila',
      isMyContact: false,
      isPSA: false,
      isUser: true,
      isWAContact: true,
      profilePicThumbObj: [Object],
      msgs: null
    },
    groupMetadata: null,
    presence: { id: '573107901940@c.us', chatstates: [] },
    isOnline: null,
    lastSeen: 1651491041000
  },
  isOnline: null,
  lastSeen: 1651491041000,
  mediaData: {},
  linkPreview: false,
  text: 'buenas',
  initialPageSize: 768
}
Result message :>> Fernando Ardila :>> OK
Message_from:  {
  id: 'false_573107901940@c.us_3EB07B73408E2AD87BF8',
  body: 'buenas',
  type: 'chat',
  t: 1651491042,
  notifyName: 'Fernando Ardila',
  from: '573107901940@c.us',
  to: '573216131576@c.us',
  self: 'in',
  ack: 1,
  isNewMsg: true,
  star: false,
  recvFresh: true,
  isFromTemplate: false,
  broadcast: false,
  mentionedJidList: [],
  isVcardOverMmsDocument: false,
  isForwarded: false,
  labels: [],
  hasReaction: false,
  ephemeralOutOfSync: false,
  productHeaderImageRejected: false,
  lastPlaybackProgress: 0,
  isDynamicReplyButtonsMsg: false,
  isMdHistoryMsg: false,
  requiresDirectConnection: false,
  pttForwardedFeaturesEnabled: true,
  chatId: '573107901940@c.us',
  fromMe: false,
  sender: {
    id: '573107901940@c.us',
    shortName: 'Fercho',
    pushname: 'Fernando Ardila',
    type: 'in',
    isBusiness: false,
    isEnterprise: false,
    labels: [],
    isContactSyncCompleted: 0,
    formattedName: '+57 310 7901940',
    displayName: 'Fernando Ardila',
    formattedShortName: 'Fercho',
    formattedShortNameWithNonBreakingSpaces: 'Fercho',
    isMe: false,
    mentionName: 'Fernando Ardila',
    notifyName: 'Fernando Ardila',
    isMyContact: false,
    isPSA: false,
    isUser: true,
    isWAContact: true,
    profilePicThumbObj: { id: '573107901940@c.us', tag: '' },
    msgs: null
  },
  timestamp: 1651491042,
  content: 'buenas',
  isGroupMsg: false,
  isMedia: false,
  isNotification: false,
  isPSA: false,
  chat: {
    id: '573107901940@c.us',
    labels: [],
    lastReceivedKey: {
      fromMe: true,
      remote: '573107901940@c.us',
      id: 'VEAIU4VBBLC7VFSOYVYR',
      _serialized: 'true_573107901940@c.us_VEAIU4VBBLC7VFSOYVYR'
    },
    t: 1651491040,
    unreadCount: 0,
    muteExpiration: 0,
    notSpam: true,
    hasUnreadMention: false,
    archiveAtMentionViewedInDrawer: false,
    hasChatBeenOpened: false,
    tcToken: {},
    tcTokenTimestamp: 1651491044,
    tcTokenSenderTimestamp: 1651491040,
    pendingInitialLoading: false,
    msgs: null,
    kind: 'chat',
    isGroup: false,
    contact: {
      id: '573107901940@c.us',
      shortName: 'Fercho',
      pushname: 'Fernando Ardila',
      type: 'in',
      isBusiness: false,
      isEnterprise: false,
      labels: [],
      isContactSyncCompleted: 0,
      formattedName: '+57 310 7901940',
      displayName: 'Fernando Ardila',
      formattedShortName: 'Fercho',
      formattedShortNameWithNonBreakingSpaces: 'Fercho',
      isMe: false,
      mentionName: 'Fernando Ardila',
      notifyName: 'Fernando Ardila',
      isMyContact: false,
      isPSA: false,
      isUser: true,
      isWAContact: true,
      profilePicThumbObj: [Object],
      msgs: null
    },
    groupMetadata: null,
    presence: { id: '573107901940@c.us', chatstates: [] },
    isOnline: null,
    lastSeen: 1651491041000
  },
  isOnline: null,
  lastSeen: 1651491041000,
  mediaData: {},
  linkPreview: false,
  text: 'buenas',
  initialPageSize: 768
}
Result message :>> Fernando Ardila :>> OK
azureuser@vmfacturacion:~$  Error: 3 INVALID_ARGUMENT: Input text not set.
